name: Flutter CI/CD with Netlify

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'  # Specify Flutter version or use 'stable'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run Flutter tests
      - name: Run tests
        run: flutter test

      # Build for Web
      - name: Build Flutter Web
        run: flutter build web

      # Deploy to Netlify
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npm install -g netlify-cli
          netlify deploy --prod --dir=build/web --site=$NETLIFY_SITE_ID
